### ISSUE TITLE
Telemetry in OCP profile should be TelemetryService

### ISSUE THREAD

**Issue by amar-shalgar** [opencomputeproject/HWMgmt-OCP-Profiles#30]
While using OCP profiles with the Redfish Interop Validator tool using 2021.2 redfish schema. Getting issue fail.Telemetry.ReadRequirement: 1 in /redfish/v1 URI. As per redfish it is TelemetryService while in the OCP profile it is looking for Telemetry. We used OCPRackManagerController.v1_0_0.json OCP profile

**Comment by jcleung5549** [comment]
Fix in #31

**Comment by amar-shalgar** [comment]
Thank you

**Comment by arahimanshaik** [comment]
@jcleung5549 Please merge the change to master

**Comment by jcleung5549** [comment]
Merging this requires approval of the PR by the OpenRMC subproject.  I have notified the project lead.  Feel free to send email to the reflector requesting this be placed on the agenda - OpenRMC@OCP-All.groups.io

**Comment by HWAymyra** [comment]
Approve. Thanks.

**Comment by jcleung5549** [comment]
Resolved in v1.0.1
