### ISSUE TITLE
Issues in Rack manager OCP profile - OCPRackManagerController.v1_1_0.json

### ISSUE THREAD

**Issue by amar-shalgar** [opencomputeproject/HWMgmt-OCP-Profiles#34]
1. BIOSVersion in OCP profile should be mentioned as BiosVersion as per Redfish specification
2. There is no property by name ManagerBy in Redfish schema, nearest we can see is ManagedBy
3. There is no property by name ManagerNetworkProtocol in Redfish schema, nearest we can see is NetworkProtocol

**Comment by jcleung5549** [comment]
Typo fixed in https://github.com/opencomputeproject/HWMgmt-OCP-Profiles/commit/b4da82a18ad2ea5368f6d899fe3466c69f284eea

**Comment by arahimanshaik** [comment]
@jcleung5549 no fix for ManagerBy?

**Comment by jcleung5549** [comment]
Fixed in PR to the v1.0.2 profile. The pull request should be approved soon.

**Comment by arahimanshaik** [comment]
Thankyou
