### ISSUE TITLE
"AssetTag" (casesensitive) is the valid property as per DMTF Redfish schema

### ISSUE THREAD

**Issue by arahimanshaik** [opencomputeproject/HWMgmt-OCP-Profiles#44]
https://github.com/opencomputeproject/HWMgmt-OCP-Profiles/blob/c17ce0d52e121681e88476bc6de9059f9a1abf98/OCPRackManagerController.v1_0_1.json#L261

**Comment by jcleung5549** [comment]
Fixed in  https://github.com/opencomputeproject/HWMgmt-OCP-Profiles/commit/b4da82a18ad2ea5368f6d899fe3466c69f284eea
