### ISSUE TITLE
ProtocolEnabled is the right property for ManagerNetworkProtocol schema

### ISSUE THREAD

**Issue by arahimanshaik** [opencomputeproject/HWMgmt-OCP-Profiles#46]
in https://github.com/opencomputeproject/HWMgmt-OCP-Profiles/blob/b47d9eb08816a2c2e7dc7272bb78cc9c9628904d/RackManager/OCPRackManagerController.v1_1_0.json#L119 and https://github.com/opencomputeproject/HWMgmt-OCP-Profiles/blob/b47d9eb08816a2c2e7dc7272bb78cc9c9628904d/RackManager/OCPRackManagerController.v1_1_0.json#L125 there seems to be a misspell as ProtocolEnabled is the correct property present in the schema

**Comment by jcleung5549** [comment]
Can you test the profile changes in pull request #47?
