### ISSUE TITLE
OCP Server Profile v1.0.1 Typo

### ISSUE THREAD

**Issue by gtossk2** [opencomputeproject/HWMgmt-OCP-Profiles#54]
OCP Server profile v1.0.1 typos : "ConditionalRequirement" -> "ConditionalRequirements"

https://github.com/opencomputeproject/HWMgmt-OCP-Profiles/blob/master/Server/OCPServerHardwareManagement.v1_0_1.json#L25
https://github.com/opencomputeproject/HWMgmt-OCP-Profiles/blob/master/Server/OCPServerHardwareManagement.v1_0_1.json#L37

**Comment by jcleung5549** [comment]
Thanks for reporting.  Would you like to create the pull request?

**Comment by gtossk2** [comment]
Created PR for review.
