### ISSUE TITLE
Typo in physical context comparison for OCPServerHardwareManagement.v1_0_1.json

### ISSUE THREAD

**Issue by plmanik** [opencomputeproject/HWMgmt-OCP-Profiles#62]
Hi,
Physical context can be one value only, but comparison used is Allof  as shown below

```
"Thermal": {
			"MinVersion": "1.1.0",
			"PropertyRequirements": {
				"Temperatures": {
					"ReadRequirement": "Mandatory",
					"MinCount": 3,
					"PropertyRequirements": {
						"ReadingCelsius": {},
						"PhysicalContext": {
							**"Comparison": "AllOf",**
							"Values": ["CPU", "Intake", "SystemBoard"]
						},
```

Eventhough value is coming as intake, due to Allof Comparison, it's failing please confirmw whether it needs to be Anyof or Allof

**Comparison.Thermal.Temperatures.PhysicalContext | AllOf | ['CPU', 'Intake', 'SystemBoard'] | ['Intake', 'Intake', 'Intake', 'Intake', 'Intake', 'Intake', 'Intake'] | FAIL**

Thanks,
Mani

**Comment by plmanik** [comment]
@jcleung5549 Do we have any plan to fix this or any update on this?

**Comment by jcleung5549** [comment]
The requirement is that there be an element in the Temperature's array with each PhysicalContext (CPU, Inlet, System).  There error message indicators that all 6 elements of the array have the same PhysicalContext, "Inlet".
