### ISSUE TITLE
Some properties under chassis are not applicable to all chassis in multi chassis servers

### ISSUE THREAD

**Issue by malhotrs** [opencomputeproject/HWMgmt-OCP-Profiles#64]
There are few properties in Chassis which not applicable to all chassis in multi chassis environment. So there is a need to have those properties added conditionally in the OCP profile.
For example "PowerState" is not applicable to a backplane chassis.

**Comment by jcleung5549** [comment]
This issue sounds like issue #53.  The solution is the establish a different baseline for components which are not full platforms.  Take a look at the pull request once it has been created.

**Comment by jcleung5549** [comment]
The conditionals are being added in PR #65.  Does that PR handle your issue?  If not, please add a comment to the pull request.

**Comment by jcleung5549** [comment]
Close as duplicate.
