### ISSUE TITLE
Redfish Baseline Profile Issues

### ISSUE THREAD

**Issue by mraineri** [opencomputeproject/HWMgmt-OCP-Profiles#80]
Wanted to put everything in one issue for discussion rather than opening several issues.

Profile version needs to be updated to 1.0.0 (unless we're still considering this as a draft and not 1.0 ready).

EthernetInterface
* IPv4Addresses needs to not specify write requirements; IPv4StaticAddresses is where users modify IPv4 addresses
    * When Redfish was originally released, IPv4Addresses was the control surface for setting IP addresses, but we've moved away from this years ago
* IPv6StaticAddresses needs property requirements for nested properties

EventDestination
* ExcludeMessageIds, ExcludeRegistryPrefixes, HttpHeaders, IncludeOriginOfCondition, RegistryPrefixes, ResourceTypes, SubordinateResources need to remove the write requirement
    * These are specified at creation time (not modifiable after creation)
* RegistryPrefixes and ResourceTypes need the read requirement loosened (maybe IfPopulated?)
    * These properties will not show up if the client does not specify these in the POST request.
    * May want to consider the same change to other properties since "Recommended" here is a bit confusing.

EventService
* ExcludeMessageId and ExcludeRegistryPrefix need the read requirement elevated to mandatory and the write requirement removed
    * This is a capability of the service and not something the client can modify

LicenseCollection and LicenseService
* Resource level read requirement should be "IfImplemented"

LogEntry and LogService
* Do we want to specify a URI pattern underneath the Manager, or keep it open?
    * Manager does require "LogServices", so adding the URI might be good for parallelism 

OutboundConnection and RegisteredClient
* Resource level read requirement should be "IfPopulated"

**Comment by jautor** [comment]
Thanks Mike - these all seem reasonable, I will adjust the profile.
From other discussions, it appears that not all network-capable devices include remote firmware update, so we will need to move the UpdateService requirements to "Recommended"

**Comment by jautor** [comment]
From Profiles workstream meeting 8/8:
- Change `DateTimeLocalOffset` to "Recommended" in LogService (not mandatory as timezone setting is done in Manager)
- Remove `NetworkSuppliedServers` from `NTP` from profile requirements
-
